### ISSUE TITLE
Summary shouldn't end with fullstop

### ISSUE THREAD

**Issue by razzeee** [flathub/com.stremio.Stremio#11]

**Comment by core1024** [comment]
Why? Can you point me were is this requirement written in the documentation?

**Comment by razzeee** [comment]
It's a recommendation, not a requirement.

The documentation is mostly worried about hard facts right now, but there is some doc coming up to help with the metadata quality. You can get a preview here: https://github.com/flathub/documentation/pull/46

There is also this blog, speaking about good practices, that mentions it directly.
https://blogs.gnome.org/tbernard/2021/09/07/ready-for-software-41/

**Comment by core1024** [comment]
Fixed in https://github.com/flathub/com.stremio.Stremio/pull/17
