### ISSUE TITLE
Description shouldn't mirror summary

### ISSUE THREAD

**Issue by razzeee** [flathub/com.stremio.Stremio#12]

**Comment by core1024** [comment]
Why? Can you point me were is this requirement written in the documentation?

**Comment by razzeee** [comment]
I don't think it's written down explicitly anywhere. 

But as these are two different fields, with different contents, they shouldn't be used for the same thing.

Your summary is a `short description` - more of a tag line preferably below 35  chars, topmost 50. One line.

Description can be as long as you want, break lines, have lists and even some formatting.

So most places showing these, will end up showing them next to each other / in context to the app name. Having the same value set for both, means users will read it twice, which isn't a good use of their time and will also mean, you likely get deranked from searches, due to reiterating.

**Comment by core1024** [comment]
Fixed in https://github.com/flathub/com.stremio.Stremio/pull/17
